name: Build and push container image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**
    tags:
      - v*
    paths:
      - sample-nodejs-app/**
      - .github/**

env:
  BUILDER: paketobuildpacks/builder:base
  REGISTRY: ghcr.io
  IMAGE_NAME: michaelvl/buildpacks

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pack CLI
        uses: buildpacks/github-actions/setup-pack@v4.1.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          sep-tags: ,
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image with pack
        run: |
          pack build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --tag ${{ steps.meta.outputs.tags }} --path sample-nodejs-app --builder ${{ env.BUILDER }} --publish

      - name: Show image data
        run: |
          docker image ls
          docker image inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
